return {
	MainTextColor = Color3.fromRGB(255, 255, 255),
	MainTextFontId = "rbxassetid://16658221428", -- builder sans

	StockFrameXSize = 600,
	StockFrameYSize = 400,

	StockFrameHeaderColor = Color3.fromRGB(0, 200, 83),
	StockFrameBackgroundColor = Color3.fromRGB(255, 234, 167),

	CloseButtonColor = Color3.fromRGB(212, 61, 63),

	PurchaseButtonColor = Color3.fromRGB(87, 199, 107),

	ElementBackgroundColor = Color3.fromRGB(255, 245, 204),
}
