return {
	MainTextColor = Color3.fromRGB(255, 255, 255),
	MainTextFontId = "rbxassetid://16658221428", -- builder sans

	StockFrameXSize = 750,
	StockFrameYSize = 500,

	StockFrameHeaderColor = Color3.fromRGB(79, 164, 238),
	StockFrameBackgroundColor = Color3.fromRGB(196, 221, 242),

	CloseButtonColor = Color3.fromRGB(212, 61, 63),

	PurchaseButtonColor = Color3.fromRGB(87, 199, 107),

	ElementBackgroundColor = Color3.fromRGB(202, 210, 215),
}
